### PR TITLE
Add Elixir starter kit

### PR DESCRIPTION
**Pull request by nesQuick**
https://github.com/nesQuick/vindinium-elixir-starter

🎉 

P.S.
I know I'm late

### CODE REVIEW

**Comment by ornicar** [comment]
I no longer host the website, btw.

**Comment by nesQuick** [comment]
good to know, who is running it? Same codebase?

**Comment by ornicar** [comment]
I'm not sure, it's been a while... could be @vjousse

**Comment by vjousse** [comment]
Ahah had to check but yes, it seems it's me :-)
Damn, some people are still using Vindinium? I need to check how to update the website, Scala and Play are strangers to me now.

**Comment by nesQuick** [comment]
Apparently yes 😁  It's a cool thing, and somehow I missed it when you folks wrote it. Sorry if this causes any trouble 🎢 This project is also fairly well linked when you search stuff like this. I came here because there was this robot challenge on HN recently, and a comment had a link to a list with similar games, and this was in there as well :)

**Comment by vjousse** [comment]
It should be merged. @nesQuick can you check that the website is still working as expected with your current bot? Thanks!

**Comment by nesQuick** [comment]
@vjousse just tested it, and it works like a charm 👍 

```bash
👌  vindinium-starter-elixir git:(master) mix run vindinium.exs n24s9nk1 training 10
Watch game at: http://vindinium.org/g0s965le
..........
Game ended – random won!
```

**Pull request merged**
